apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 80;
      index index.php index.html;
      root /usr/share/nginx/html;
    }
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Code.education Rocks</title>
      </head>
      <body>
        Code.education Rocks
      </body>
    </html>
